# Generated by Django 5.0.1 on 2024-02-04 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0002_valores_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valores',
            name='categoria',
        ),
    ]
