# Generated by Django 5.0.1 on 2024-02-04 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0003_remove_valores_categoria'),
        ('perfil', '0009_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='valores',
            name='categoria',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='perfil.categoria'),
            preserve_default=False,
        ),
    ]
