# Generated by Django 5.0.1 on 2024-02-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0004_valores_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valores',
            name='categoria',
        ),
    ]
