# Generated by Django 5.0.1 on 2024-02-04 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_remove_contapagar_categoria'),
        ('extrato', '0003_remove_valores_categoria'),
        ('perfil', '0007_categoria_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
