# Generated by Django 5.0.1 on 2024-02-04 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_contapaga_user_contapagar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='categoria',
        ),
    ]
